package com.llyod.domain.model.register

import java.io.File

data class RegisterRequestModel(
    val aadhaar_number: String?,
    val account_no: String?,
    val applicant_name: String?,
    val branch_name: String?,
    val colony_area: String?,
    val district: String?,
    val dob: String?,
    val doj: String?,
    val email: String?,
    val father_name: String?,
    val gender: String?,
    val house_flat_no: String?,
    val ifsc_code: String?,
    val is_address_same: String?,
    val landmark: String?,
    val mobile: String?,
    val nominee_account_no: String?,
    val nominee_age: String?,
    val nominee_branch: String?,
    val nominee_ifsc_code: String?,
    val nominee_name: String?,
    val nominee_relation: String?,
    val office_address: String?,
    val other_qualification: String?,
    val pan_number: String?,
    val pincode: String?,
    val primary_company: String?,
    val primary_working_id: String?,
    val profile_image: File?,
    val qualification: String?,
    val service: String?,
    val state: String?,
    val street_name: String?,
    val temp_colony_area: String?,
    val temp_district: String?,
    val temp_house_no: String?,
    val temp_landmark: String?,
    val temp_pincode: String?,
    val temp_state: String?,
    val temp_street_name: String?,
    val vehicle: String? = "1",
    val worker_type: String?,
    val working_hours: String?,
    val working_type: String
)